In [1]:
import numpy as np
import pandas as pd

In [1]:
#Q1

name = input("Enter your name : ")
age = int(input("Enter your age : "))
print(f"Name is {name} and Age is {age}")

Enter your name : Vidhya Sagar
Enter your age : 21
Name is Vidhya Sagar and Age is 21


In [3]:
#Q2

x = "Datascience is used to extract meaningful insights."
x.split()

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']

In [2]:
#Q3

def mul(x,y):
  return x*y

a = int(input("Enter the first number : "))
b = int(input("Enter the second number : "))
m = mul(a,b)
print(f"Multiplication of {a} and {b} is {m}")  

Enter the first number : 2
Enter the second number : 4
Multiplication of 2 and 4 is 8


In [5]:
#Q4

states_capitals = {
    "Tamil Nadu" : "Chennai",
    "Kerala" : "Thiruvananthapuram",
    "Maharashtra" : "Mumbai",
    "Karnataka" : "Bangalore",
    "Telangana" : "Hyderabad"
}
states_capitals.keys()

dict_keys(['Tamil Nadu', 'Kerala', 'Maharashtra', 'Karnataka', 'Telangana'])

In [6]:
#Q4

states_capitals.values()

dict_values(['Chennai', 'Thiruvananthapuram', 'Mumbai', 'Bangalore', 'Hyderabad'])

In [7]:
#Q5

num = list(range(1000))
print("The range of numbers: ")
print(num)

The range of numbers: 
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 2

In [8]:
#Q6

d = np.eye(4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
#Q7

arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#Q8

arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(10,19).reshape(3,3)
arr3 = arr1+arr2
arr3

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [32]:
#Q9

date_range = pd.date_range('2023-02-01','2023-03-01')
date_range1 = pd.Series(date_range)
date_range1

0    2023-02-01
1    2023-02-02
2    2023-02-03
3    2023-02-04
4    2023-02-05
5    2023-02-06
6    2023-02-07
7    2023-02-08
8    2023-02-09
9    2023-02-10
10   2023-02-11
11   2023-02-12
12   2023-02-13
13   2023-02-14
14   2023-02-15
15   2023-02-16
16   2023-02-17
17   2023-02-18
18   2023-02-19
19   2023-02-20
20   2023-02-21
21   2023-02-22
22   2023-02-23
23   2023-02-24
24   2023-02-25
25   2023-02-26
26   2023-02-27
27   2023-02-28
28   2023-03-01
dtype: datetime64[ns]

In [11]:
#Q10

dictionary = {
    'Brand' : ["Maruti","Renault","Hyndai"],
    'Sales' : [250,200,240]
}
df = pd.DataFrame(dictionary)
df

Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240